name: Deprecated • Pack → Install (use Test Package Installation)

on:
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This workflow is deprecated. Use 'Test Package Installation' instead."
