name: Docs Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docs-executor:
    name: Executable Docs (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        node-version: [24]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build project
        run: npm run build
      
      - name: Run docs executor
        run: node dist/scripts/docs-executor.js .
        continue-on-error: false
      
      - name: Upload sandbox artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: docs-executor-logs-${{ matrix.os }}-node${{ matrix.node-version }}
          path: |
            /tmp/laminar-docs-*
          retention-days: 7
  
  link-lint:
    name: Link Linting (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        node-version: [24]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build project
        run: npm run build
      
      - name: Run link linter
        run: node dist/scripts/link-lint.js .
        continue-on-error: false
      
      - name: Report broken links
        if: failure()
        run: |
          echo "::error::Link validation failed. Check the logs above for broken links."
          exit 1
