name: Install Validate (GitHub install)
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  github-install-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build Laminar
        run: |
          npm ci
          npm run build

      - name: Create temp consumer project
        run: |
          mkdir -p /tmp/laminar-consumer && cd /tmp/laminar-consumer
          npm init -y
          npm install -D vitest@1
          echo "export default { test: { } }" > vitest.config.mjs
          mkdir -p tests
          cat > tests/smoke.spec.ts << 'EOF'
          import { describe, it, expect } from 'vitest';
          describe('smoke', () => {
            it('works', () => { expect(1+1).toBe(2); });
          });
          EOF

      - name: Install Laminar from GitHub
        working-directory: /tmp/laminar-consumer
        run: |
          npm install -D github:anteew/Laminar

      - name: Resolve reporter path
        id: reporter
        working-directory: /tmp/laminar-consumer
        run: |
          node -e "
            const fs=require('fs'), path=require('path');
            function search(dir){
              try{
                const ents=fs.readdirSync(dir,{withFileTypes:true});
                for(const ent of ents){
                  const full=path.join(dir, ent.name);
                  if(ent.isDirectory()){
                    const cand=path.join(full, 'dist/src/test/reporter/jsonlReporter.js');
                    if(fs.existsSync(cand)) return cand;
                    const res=search(full);
                    if(res) return res;
                  }
                }
              }catch{}
              return null;
            }
            let p=null;
            try{ p=require.resolve('@agent_vega/laminar/dist/src/test/reporter/jsonlReporter.js'); }catch{}
            if(!p){ try{ p=require.resolve('laminar/dist/src/test/reporter/jsonlReporter.js'); }catch{} }
            if(!p){ p=search(path.resolve(process.cwd(),'node_modules')); }
            if(!p){ console.error('Unable to resolve reporter path'); process.exit(2); }
            console.log('REPORTER='+p);
          " >> $GITHUB_ENV
          echo "Reporter is: $REPORTER"

      - name: Run Laminar
        working-directory: /tmp/laminar-consumer
        env:
          LAMINAR_REPORTER_PATH: ${{ env.REPORTER }}
        run: |
          npx lam init
          npx vitest run --reporter="$LAMINAR_REPORTER_PATH"
          npx lam summary

      - name: Validate artifacts
        working-directory: /tmp/laminar-consumer
        run: |
          test -f reports/summary.jsonl
          ls -R reports || true
