# This workflow tests the actual user journey: installing from GitHub
# This is critical because it catches issues that only happen when users
# install with: npm install -D github:anteew/Laminar

name: Test GitHub Installation

on:
  workflow_call:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test-github-install:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        node-version: [24]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Create a fresh test directory that simulates a user's project
      - name: Create test project
        run: |
          mkdir -p /tmp/test-project/logs
          cd /tmp/test-project
          npm init -y

      # Test installing from the current branch/commit
      # This simulates: npm install -D github:anteew/Laminar#branch-name
      - name: Install package from GitHub (current commit)
        run: |
          cd /tmp/test-project
          npm install -D $GITHUB_WORKSPACE

      # Verify package.json exists in installed package
      - name: Verify package.json exists in installation
        run: |
          if [ ! -f /tmp/test-project/node_modules/@agent_vega/laminar/package.json ]; then
            echo "ERROR: package.json missing from installed package!"
            exit 1
          fi
          echo "✓ package.json found in installation"

      # Verify dist files exist
      - name: Verify dist files exist
        run: |
          if [ ! -f /tmp/test-project/node_modules/@agent_vega/laminar/dist/scripts/lam.js ]; then
            echo "ERROR: dist/scripts/lam.js missing!"
            exit 1
          fi
          if [ ! -f /tmp/test-project/node_modules/@agent_vega/laminar/dist/scripts/mcp-server.js ]; then
            echo "ERROR: dist/scripts/mcp-server.js missing!"
            exit 1
          fi
          echo "✓ All required dist files found"

      # Test lam command works
      - name: Test lam command
        run: |
          cd /tmp/test-project
          npx lam --help > logs/lam-help.stdout 2> logs/lam-help.stderr
          STATUS=$?
          if [ $STATUS -ne 0 ]; then
            echo "ERROR: lam command failed!"
            exit $STATUS
          fi
          echo "✓ lam command works"

      # Test laminar-mcp --help exits immediately with 0
      - name: Test laminar-mcp --help exits immediately
        shell: bash
        run: |
          cd /tmp/test-project
          python3 - << 'PYCODE'
          import subprocess, sys
          out_path = "/tmp/test-project/logs/laminar-mcp-help.stdout"
          err_path = "/tmp/test-project/logs/laminar-mcp-help.stderr"
          try:
              with open(out_path, "wb") as out, open(err_path, "wb") as err:
                  p = subprocess.Popen(["npx", "laminar-mcp", "--help"], stdout=out, stderr=err)
                  try:
                      p.wait(timeout=5)
                  except subprocess.TimeoutExpired:
                      p.kill()
                      sys.exit(124)
                  sys.exit(p.returncode)
          except Exception as e:
              sys.stderr.write(str(e) + "\n")
              sys.exit(1)
          PYCODE
          exit_code=$?
          if [ $exit_code -ne 0 ]; then
            echo "ERROR: laminar-mcp --help must exit with 0, got exit code $exit_code"
            echo "If timeout (124), the command is not exiting immediately as required"
            exit 1
          fi
          echo "✓ laminar-mcp --help exits immediately with 0"

      # Test that lam init works
      - name: Test lam init
        run: |
          cd /tmp/test-project
          npx lam init --template minimal
          if [ ! -f laminar.config.json ]; then
            echo "ERROR: lam init failed to create config!"
            exit 1
          fi
          echo "✓ lam init works"

      # Verify all bin symlinks are valid
      - name: Verify bin symlinks
        run: |
          cd /tmp/test-project
          PY_REALPATH='import os,sys;print(os.path.realpath(sys.argv[1]))'
          LAM_BIN=$(python3 -c "$PY_REALPATH" node_modules/.bin/lam)
          MCP_BIN=$(python3 -c "$PY_REALPATH" node_modules/.bin/laminar-mcp)
          
          echo "lam symlink points to: $LAM_BIN"
          echo "laminar-mcp symlink points to: $MCP_BIN"
          
          if [ ! -f "$LAM_BIN" ]; then
            echo "ERROR: lam symlink points to non-existent file!"
            exit 1
          fi
          
          if [ ! -f "$MCP_BIN" ]; then
            echo "ERROR: laminar-mcp symlink points to non-existent file!"
            exit 1
          fi
          
          echo "✓ All bin symlinks valid"

      # List installed package contents for debugging
      - name: Debug - List package contents
        if: failure()
        run: |
          echo "=== Installed package contents ==="
          ls -laR /tmp/test-project/node_modules/@agent_vega/laminar/
          
          echo "=== Package.json location ==="
          find /tmp/test-project/node_modules/@agent_vega/laminar -name "package.json"
          
          echo "=== JavaScript files ==="
          find /tmp/test-project/node_modules/@agent_vega/laminar -name "*.js" | head -20
      - name: Collect symlink resolution notes
        if: failure()
        run: |
          cd /tmp/test-project
          mkdir -p logs
          PY_REALPATH='import os,sys;print(os.path.realpath(sys.argv[1]))'
          python3 -c "$PY_REALPATH" node_modules/.bin/lam > logs/lam.realpath.txt 2>&1 || true
          python3 -c "$PY_REALPATH" node_modules/.bin/laminar-mcp > logs/laminar-mcp.realpath.txt 2>&1 || true

      - name: Upload failure artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: github-install-debug-${{ matrix.os }}-node${{ matrix.node-version }}
          path: |
            /tmp/test-project/node_modules/@agent_vega/laminar/**
            /tmp/test-project/node_modules/.bin/**
            /tmp/test-project/logs/**
          if-no-files-found: warn
