# This workflow tests that the package can be installed by end users
# It simulates the npm publish + install flow to catch issues like:
# - prepare/install hooks that require source files not in the published package
# - Missing dist files
# - Broken CLI entry points

name: Test Package Installation

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test-install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Pack package
        run: npm pack

      - name: Create test directory
        run: mkdir -p /tmp/test-install

      - name: Install from tarball
        run: |
          cd /tmp/test-install
          npm install $GITHUB_WORKSPACE/*.tgz

      - name: Test CLI works
        run: |
          cd /tmp/test-install
          npx lam --help
